name: Build and push dev image

on:
  push:
    branches:
      - dev
# Trigger workflow on push to the "dev" branch

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    # Runner OS

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        # Checkout the repository

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        # Log in to Docker Hub using credentials stored in GitHub secrets

      - name: Build image
        run: docker image build -t ahmedevops/simplewebdev -f Dockerfile.dev .
        # Build Docker image from the Dockerfile.dev

      - name: Push image
        run: docker image push ahmedevops/simplewebdev
        # Push the Docker image to Docker Hub
