name: Deploy application image

on:
  pull_request:
    types:
      - closed
    branches:
      - master
# Trigger workflow when a pull request is closed and merged into the master branch

jobs:
  deploy-app:
    if: ${{ github.event.pull_request.merged == true }}
    # Run job only if the pull request is merged

    runs-on: ubuntu-latest
    # Runner OS

    steps:
      - uses: actions/checkout@v1
        # Checkout the repository

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        # Log in to Docker Hub using GitHub secrets

      - run: docker image build -t ahmedevops/simplewebprod .
        # Build the Docker image from the repository

      - run: docker image push ahmedevops/simplewebprod
        # Push the Docker image to Docker Hub
      - name: Deploy App Render Container
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: ing2isimm2024/simplewebprod:latest
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true

